### ISSUE TITLE
Is this extension still maintained?

### ISSUE THREAD

**Issue by kingosticks** [rattboi/mopidy-subsonic#17]
@rattboi are you still maintaining and supporting this extension? I completely understand if it's no longer of interest for you - in which case, could you make that clear and post a maintainer request in the README? Thanks.

**Comment by kingosticks** [comment]
I'm going to take this as a "no".

**Comment by rattboi** [comment]
Sorry, no, I'm no longer maintaining this. I'm not using Subsonic OR mopidy at this point. It's too bad nobody took over a fork instead.

**Comment by hhm0** [comment]
@rattboi Thank you for letting us know! :-) And thanks for updating the README to clarify this. Thanks for paving the way for subsonic support in mopidy :-)
