### ISSUE TITLE
mopidy_subsonic.client: Subsonic Authentication error: Required parameter is missing

### ISSUE THREAD

**Issue by mrpurplenz** [rattboi/mopidy-subsonic#22]
I have an ampache based subsonic server which responds correctly to the android subsonic client at
http://sub.mydomain.com
port: 80
username = myusername
password = mypassword
context = /
however as with the title the log gives an error and kills mopidy
any ideas?

**Comment by hhm0** [comment]
It seems that this may be because  Ampache only supports "old"-style auth, while `libsonic` (which `mopidy-subsonic` uses) only supports the "new"-style auth.

See crustymonkey/py-sonic/issues/17 for more details.

**Comment by hhm0** [comment]
Does pull #24 fix this? Be sure to upgrade `py-sonic` too before testing :-).

**Comment by mrpurplenz** [comment]
Not yet. The error message is more informative now however.

> libsonic.errors.VersionError: Incompatible Subsonic REST protocol version. Server must upgrade.

Time to go begging, cap-in-hand, to the ampache team.

**Comment by mrpurplenz** [comment]
Actually the last error resulted from ampache detecting a higher api version than reported by pysonic, having set legacyAuth.

**Comment by mrpurplenz** [comment]
Yes. I manually made the changes in pull #24 to my mopidy-subsonic plugin and authentication works provided that the version is manually set to 1.11.0 in libsonic/connection.py. So I'll close _this_ issue.
However now mopidy reports `SubsonicBackend does not implement playlists.as_list().` So I'll open a new issue for that.
